# Generated by Django 4.1 on 2023-04-18 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commons', '0002_alter_bank_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Nombre')),
                ('btype', models.CharField(choices=[('PRV', 'Privado'), ('GOB', 'Gobierno')], max_length=4, verbose_name='Tipo')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Dirección')),
                ('min_payment', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Pago Mínimo')),
                ('max_payment', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Pago Máximo')),
                ('credit_term', models.PositiveIntegerField(db_index=True, help_text='Plazo en Meses', verbose_name='Plazo del Crédito')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ctype', models.CharField(choices=[('AUTO', 'Automotriz'), ('HIPO', 'Hipotecarios'), ('COMER', 'Comerciales')], max_length=5, verbose_name='Tipo de Crédito')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credits.bank', verbose_name='Banco que otorgante')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.client', verbose_name='Cliente')),
            ],
        ),
    ]
