# Generated by Django 4.1 on 2023-04-19 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='Monto del crédito'),
            preserve_default=False,
        ),
    ]
