# Generated by Django 4.1 on 2023-04-18 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Nombre')),
                ('btype', models.CharField(choices=[('PRV', 'Privado'), ('GOB', 'Gobierno')], default='PRCS', max_length=4, verbose_name='Tipo')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=50, verbose_name='Nombre')),
                ('birthdate', models.DateField(db_index=True, verbose_name='Fecha Nacimiento')),
                ('years_old', models.PositiveIntegerField(db_index=True, verbose_name='Edad')),
                ('nationality', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Nacionalidad')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección de habitación')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('ptype', models.CharField(choices=[('NTR', 'Natural'), ('JRD', 'Juridico')], default='PRCS', max_length=4, verbose_name='Tipo de Persona')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.bank', verbose_name='Banco')),
            ],
        ),
    ]
