# Generated by Django 4.1 on 2023-04-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=50, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
