# Generated by Django 4.1 on 2023-04-18 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
        ('commons', '0002_alter_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credits.bank', verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='client',
            name='ptype',
            field=models.CharField(choices=[('NTR', 'Natural'), ('JRD', 'Juridico')], max_length=4, verbose_name='Tipo de Persona'),
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
    ]
